backend/project/blog/views.py
from sys import prefix
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from project.blog.froms import PostForm
from project import db

# from decorators import login_required
from project.models import BlogPost

bp = Blueprint("blog", __name__, template_folder='templates', url_prefix='/blog')

def getPosts():
    # cur = db.execute("SELECT * FROM posts;")
    # posts = [dict(title=row[0], description=row[1]) for row in cur.fetchall()]
    # db.close()
    posts = []
    posts = BlogPost.query.all()
    return posts

@bp.route('/')
def show_posts():
    posts = getPosts()
    return render_template('show_posts.html', posts=posts)


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm(request.form)
    if form.validate_on_submit():
        post = BlogPost( 
                        title=form.title.data,
                        description=form.description.data,
                        author_id=current_user.id
                        )
        
        db.session.add(post)

        try:
            db.session.commit()
            return redirect(url_for('home.home'))
        except Exception:
            db.session.rollback()
        finally:
            db.session.close()
    
    return render_template('create.html', form=form)

backend/project/blog/templates/create.html
{% extends "base.html" %} {% block content %}

<!-- post form -->
<h3>Add a Post!</h3>
<br />
<form
  class="form-message"
  role="form"
  method="post"
  action="{{ url_for('blog.create_post') }}"
>
  {{ form.csrf_token }}
  <p>
    {{ form.title(placeholder="title") }}
    <span class="error">
      {% if form.title.errors %} {% for error in form.title.errors %} {{ error
      }} {% endfor %} {% endif %}
    </span>
  </p>
  <p>
    {{ form.description(placeholder="description") }}
    <span class="error">
      {% if form.description.errors %} {% for error in form.description.errors
      %} {{ error }} {% endfor %} {% endif %}
    </span>
  </p>
  <button class="btn btn-sm btn-success" type="submit">Post</button>
</form>
{% endblock %}

backend/project/blog/templates/show_posts.html
{% extends "base.html" %} {% block content %}

<!-- All posts -->
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for post in posts %}

      <div class="col">
        <div class="card shadow-sm">
          <img
            class="bd-placeholder-img card-img-top"
            width="100%"
            height="225"
           src="{{ url_for('static', filename='images/blog'+post.id|string+'.jpg')}}"
          >
            <title>'{post.title}}</title>
            <rect width="100%" height="100%" fill="#55595c" />
          </svg>

          <div class="card-body">
            <p class="card-text">{{ post.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  View
                </button>
              </div>
              <small class="text-muted">{{ post.author.name }}, 9 mins</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}