backend/project/store/forms.py
from tokenize import String
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired


class ProductForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    description = StringField("Description", validators=[DataRequired()])
    price = StringField("Price", validators=[DataRequired()])

backend/project/store/views.py
from itertools import product
from sys import prefix
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from project import db

# from decorators import login_required
from project.models import Product
from project.store.forms import ProductForm

bp = Blueprint("store", __name__, template_folder='templates', url_prefix='/store')

def getProducts():
    # cur = db.execute("SELECT * FROM posts;")
    # posts = [dict(title=row[0], description=row[1]) for row in cur.fetchall()]
    # db.close()
    products = []
    products = Product.query.all()
    return products

@bp.route('/')
def show_products():
    products = getProducts()
    return render_template('show_products.html', products=products)


@bp.route('/product/add', methods=['GET', 'POST'])
@login_required
def create_product():
    form = ProductForm(request.form)
    if form.validate_on_submit():
        product = Product( 
                        title=form.title.data,
                        description=form.description.data,
                        price=form.price.data
                        )
        
        db.session.add(product)

        try:
            db.session.commit()
            return redirect(url_for('home.home'))
        except Exception:
            db.session.rollback()
        finally:
            db.session.close()
    
    return render_template('create_product.html', form=form)

backend/project/store/templates/create.html
{% extends "base.html" %} {% block content %}

<!-- post form -->
<h3>Add a Product!</h3>
<br />
<form
  class="form-message"
  role="form"
  method="post"
  action="{{ url_for('blog.create_product') }}"
>
  {{ form.csrf_token }}
  <p>
    {{ form.title(placeholder="title") }}
    <span class="error">
      {% if form.title.errors %} {% for error in form.title.errors %} {{ error
      }} {% endfor %} {% endif %}
    </span>
  </p>
  <p>
    {{ form.description(placeholder="description") }}
    <span class="error">
      {% if form.description.errors %} {% for error in form.description.errors
      %} {{ error }} {% endfor %} {% endif %}
    </span>
  </p>
  <p>
    {{ form.price(placeholder="price") }}
    <span class="error">
      {% if form.price.errors %} {% for error in form.price.errors %} {{ error
      }} {% endfor %} {% endif %}
    </span>
  </p>
  <button class="btn btn-sm btn-success" type="submit">Add</button>
</form>
{% endblock %}

backend/project/store/templates/create_product.html
{% extends "base.html" %} {% block content %}

<!-- post form -->
<h3>Add a Product!</h3>
<br />
<form
  class="form-message"
  role="form"
  method="post"
  action="{{ url_for('store.create_product') }}"
>
  {{ form.csrf_token }}
  <p>
    {{ form.title(placeholder="title") }}
    <span class="error">
      {% if form.title.errors %} {% for error in form.title.errors %} {{ error
      }} {% endfor %} {% endif %}
    </span>
  </p>
  <p>
    {{ form.description(placeholder="description") }}
    <span class="error">
      {% if form.description.errors %} {% for error in form.description.errors
      %} {{ error }} {% endfor %} {% endif %}
    </span>
  </p>
  <p>
    {{ form.price(placeholder="price") }}
    <span class="error">
      {% if form.price.errors %} {% for error in form.price.errors %} {{ error
      }} {% endfor %} {% endif %}
    </span>
  </p>
  <button class="btn btn-sm btn-success" type="submit">Add</button>
</form>
{% endblock %}

backend/project/store/templates/show_products.html
{% extends 'base.html' %} {% block content %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for product in products %}

      <div class="col">
        <div class="card shadow-sm">
          <img
            class="bd-placeholder-img card-img-top"
            width="100%"
            height="225"
            src="{{ url_for('static', filename='images/product'+product.id|string+'.jpeg')}}"
            role="img"
            aria-label="Placeholder: Thumbnail"
            preserveAspectRatio="xMidYMid slice"
            focusable="false"
          >
            <title>{{ product.title }}</title>
            <rect width="100%" height="100%" fill="#55595c" />
          </svg>

          <div class="card-body">
            <p class="card-text">{{ product.description }}</p>
            <p class="card-text">{{ product.price }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  <a href="mailto:tripal.tinvr@gmail.com">I want to try it</a>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}