backend/project/blog/views.py
from sys import prefix
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from project.blog.froms import PostForm
from project import db

# from decorators import login_required
from project.models import BlogPost

bp = Blueprint("blog", __name__, template_folder='templates', url_prefix='/blog')

def getPosts():
    # cur = db.execute("SELECT * FROM posts;")
    # posts = [dict(title=row[0], description=row[1]) for row in cur.fetchall()]
    # db.close()
    posts = []
    posts = BlogPost.query.all()
    return posts

@bp.route('/')
def show_posts():
    posts = getPosts()
    return render_template('show_posts.html', posts=posts)


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm(request.form)
    if form.validate_on_submit():
        post = BlogPost( 
                        title=form.title.data,
                        description=form.description.data,
                        author_id=current_user.id
                        )
        
        db.session.add(post)

        try:
            db.session.commit()
            return redirect(url_for('home.home'))
        except Exception:
            db.session.rollback()
        finally:
            db.session.close()
    
    return render_template('create.html', form=form)

backend/project/experience/views.py
from sys import prefix
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from project import db
from project.experience.forms import ExperienceForm

# from decorators import login_required
from project.models import Experience, Reservation

bp = Blueprint("experience", __name__, template_folder='templates', url_prefix='/experience')

def getExperiences():
    # cur = db.execute("SELECT * FROM posts;")
    # posts = [dict(title=row[0], description=row[1]) for row in cur.fetchall()]
    # db.close()
    posts = []
    posts = Experience.query.all()
    return posts

@bp.route('/')
def show_experiences():
    posts = getExperiences()
    return render_template('show_experiences.html', experiences=posts)


@bp.route('/experience/add', methods=['GET', 'POST'])
@login_required
def create_experience():
    form = ExperienceForm(request.form)
    if form.validate_on_submit():
        post = Experience( 
                        title=form.title.data,
                        description=form.description.data,
                        price = form.price.data
                        )
        
        db.session.add(post)

        try:
            db.session.commit()
            return redirect(url_for('home.home'))
        except Exception:
            db.session.rollback()
        finally:
            db.session.close()
    
    return render_template('create_experience.html', form=form)

backend/project/home/views.py
from sys import prefix
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from project.blog.froms import PostForm
from project import db

# from decorators import login_required
from project.models import BlogPost

bp = Blueprint("home", __name__, template_folder='templates')


@bp.route('/', methods=["GET", "POST"])
def home():
    return render_template('index.html')


@bp.route('/vr')
def vr():
    return render_template('vr.html')

@bp.route('/pricing')
def pricing():
    return render_template('pricing.html')

backend/project/store/views.py
from itertools import product
from sys import prefix
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from project import db

# from decorators import login_required
from project.models import Product
from project.store.forms import ProductForm

bp = Blueprint("store", __name__, template_folder='templates', url_prefix='/store')

def getProducts():
    # cur = db.execute("SELECT * FROM posts;")
    # posts = [dict(title=row[0], description=row[1]) for row in cur.fetchall()]
    # db.close()
    products = []
    products = Product.query.all()
    return products

@bp.route('/')
def show_products():
    products = getProducts()
    return render_template('show_products.html', products=products)


@bp.route('/product/add', methods=['GET', 'POST'])
@login_required
def create_product():
    form = ProductForm(request.form)
    if form.validate_on_submit():
        product = Product( 
                        title=form.title.data,
                        description=form.description.data,
                        price=form.price.data
                        )
        
        db.session.add(product)

        try:
            db.session.commit()
            return redirect(url_for('home.home'))
        except Exception:
            db.session.rollback()
        finally:
            db.session.close()
    
    return render_template('create_product.html', form=form)

backend/project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta
      name="author"
      content="Mark Otto, Jacob Thornton, and Bootstrap contributors"
    />
    <meta name="generator" content="Hugo 0.98.0" />
    <title>TriPal</title>

    <link
      href="{{ url_for('static', filename='css/style.css') }}"
      rel="stylesheet"
    />
    <!--<link
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
      rel="stylesheet"
    />-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />

    <!-- Favicons -->
    <link
      rel="apple-touch-icon"
      href="/docs/5.2/assets/img/favicons/apple-touch-icon.png"
      sizes="180x180"
    />
    <link
      rel="icon"
      href="/docs/5.2/assets/img/favicons/favicon-32x32.png"
      sizes="32x32"
      type="image/png"
    />
    <link
      rel="icon"
      href="/docs/5.2/assets/img/favicons/favicon-16x16.png"
      sizes="16x16"
      type="image/png"
    />
    <link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json" />
    <link
      rel="mask-icon"
      href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg"
      color="#712cf9"
    />
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico" />
    <meta name="theme-color" content="#712cf9" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, 0.1);
        border: solid rgba(0, 0, 0, 0.15);
        border-width: 1px 0;
        box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1),
          inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -0.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>
  </head>
  <body>
    

    <div class="container py-3">
      <header>
        <div
          class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom"
        >
          <a
            href="/"
            class="d-flex align-items-center text-dark text-decoration-none"
          >
            <img
              src="{{ url_for('static', filename='images/logo.png') }}"
              alt="logo"
              height="62px"
            />
              <title>Bootstrap</title>
              <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                fill="currentColor"
              ></path>
            </svg>
            <span class="fs-4">TriPal</span>
          </a>

          <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <a class="me-3 py-2 text-dark text-decoration-none under" href="{{ url_for('home.vr') }}"
              >VR visits</a
            >
            <a class="me-3 py-2 text-dark text-decoration-none under" href="#"
              >Destinations</a
            >
            <a class="me-3 py-2 text-dark text-decoration-none under" href="{{ url_for('experience.show_experiences') }}"
              >Experience it!</a
            >
            <a class="me-3 py-2 text-dark text-decoration-none under" href="{{ url_for('store.show_products') }}"
              >Find souvenirs!</a
            >
            <a class="me-3 py-2 text-dark text-decoration-none under" href="{{ url_for('home.pricing') }}">Pricing</a>
            <a
              class=" me-3 py-2 text-dark text-decoration-none under"
              href="{{ url_for('blog.show_posts') }}"
              >Blog</a
            >
            <a
              class=" me-3 py-2 text-dark text-decoration-none under"
              href="https://web.facebook.com/Tripal2022" target="_blank"
              >Facebook</a
            >
            <a
              class=" me-3 py-2 text-dark text-decoration-none under"
              href="https://www.instagram.com/tripalv1.0/" target="_blank"
              >Instagram</a
            >
            {% if current_user.is_authenticated %}
            <a
              class="py-2 text-dark text-decoration-none under"
              href="{{ url_for('auth.logout') }}"
              >Hi, {{current_user.name[:8]}}, Log Out</a
            >
            {% else %}
            <a
              class="py-2 text-dark text-decoration-none under"
              href="{{ url_for('auth.login') }}"
              >Log In</a
            >
            {% endif %}
          </nav>
        </div>

        {% block header %}{% endblock %}
      </header>

      <main>
        <!-- child template -->
        {% block content %}{% endblock %}

        <!-- errors -->
        {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </main>

      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
            <img
              class="mb-2"
              src="{{ url_for('static', filename='images/logo.png') }}"
              alt=""
              width="92"
              height="102"
            />
            <small class="d-block mb-3 text-muted">&copy; Mirai.is... 2022 All right reserved.</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Cool stuff</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Random feature</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Team feature</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Stuff for developers</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Another one</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Last time</a
                >
              </li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Resource</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Resource name</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Another resource</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Final resource</a
                >
              </li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#">Team</a>
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Locations</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Privacy</a
                >
              </li>
              <li class="mb-1">
                <a class="link-secondary text-decoration-none" href="#"
                  >Terms</a
                >
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
  </body>
</html>