backend/project/home/views.py
from sys import prefix
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from project.blog.froms import PostForm
from project import db

# from decorators import login_required
from project.models import BlogPost

bp = Blueprint("home", __name__, template_folder='templates')


@bp.route('/', methods=["GET", "POST"])
def home():
    return render_template('index.html')


@bp.route('/vr')
def vr():
    return render_template('vr.html')

@bp.route('/pricing')
def pricing():
    return render_template('pricing.html')

backend/project/home/templates/index.html
{% extends "base.html" %} {% block content %}

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
  <div class="carousel-indicators">
    <button
      type="button"
      data-bs-target="#carouselExampleCaptions"
      data-bs-slide-to="0"
      class="active"
      aria-current="true"
      aria-label="Slide 1"
    ></button>
    <button
      type="button"
      data-bs-target="#carouselExampleCaptions"
      data-bs-slide-to="1"
      aria-label="Slide 2"
    ></button>
    <button
      type="button"
      data-bs-target="#carouselExampleCaptions"
      data-bs-slide-to="2"
      aria-label="Slide 3"
    ></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img
        src="{{ url_for('static', filename='images/tinghir1.jpg') }}"
        class="d-block w-100 carousel-img"
        alt="..."
      />
      <div class="carousel-caption d-none d-md-block caption-bg">
        <h1 class="display-4 fw-normal">TriPal</h1>
        <h3>
          Your Best Trip Pal. <br />
          We help YOU to quickly find potential destinations and experiences
          around Tinghir.
        </h3>
      </div>
    </div>
    <div class="carousel-item">
      <img
        src="{{ url_for('static', filename='images/tinghir2.webp') }}"
        class="d-block w-100 carousel-img"
        alt="..."
      />
      <div class="carousel-caption d-none d-md-block caption-bg">
        <h1 class="display-4 fw-normal">TriPal</h1>
        <h3>
          Your Best Trip Pal. <br />
          We help YOU to quickly find potential destinations and experiences
          around Tinghir.
        </h3>
      </div>
    </div>
    <div class="carousel-item">
      <img
        src="{{ url_for('static', filename='images/tinghir3.jpg') }}"
        class="d-block w-100 carousel-img"
        alt="..."
      />
      <div class="carousel-caption d-none d-md-block caption-bg">
        <h1 class="display-4 fw-normal">TriPal</h1>
        <h3>
          Your Best Trip Pal. <br />
          We help YOU to quickly find potential destinations and experiences
          around Tinghir.
        </h3>
      </div>
    </div>
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-bs-target="#carouselExampleCaptions"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-bs-target="#carouselExampleCaptions"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

{% endblock %}

backend/project/home/templates/pricing.html
{% extends "base.html" %} {% block content %}
<svg xmlns="http://www.w3.org/2000/svg" style="display: none">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path
      d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"
    />
  </symbol>
</svg>
<header>
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">Pricing</h1>
    <p class="fs-5 text-muted">
      Quickly build an effective pricing table for your potential customers with
      this Bootstrap example. It’s built with default Bootstrap components and
      utilities with little customization.
    </p>
  </div>
</header>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
      <div class="card-header py-3">
        <h4 class="my-0 fw-normal">Free</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">
          $0<small class="text-muted fw-light">/mo</small>
        </h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>No VR included</li>
          <li>Basic services</li>
          <li>Email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="w-100 btn btn-lg btn-outline-primary">
          <a href="mailto:tripal.tinvr@gmail.com">Sign up for free</a>
        </button>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
      <div class="card-header py-3">
        <h4 class="my-0 fw-normal">Pro</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">
          $15<small class="text-muted fw-light">/mo</small>
        </h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>2 users included</li>
          <li>VR Quality Standard</li>
          <li>Priority email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="w-100 btn btn-lg btn-primary">
          <a href="mailto:tripal.tinvr@gmail.com">Get started</a>
        </button>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm border-primary">
      <div class="card-header py-3 text-white bg-primary border-primary">
        <h4 class="my-0 fw-normal">Enterprise</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">
          $29<small class="text-muted fw-light">/mo</small>
        </h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>20 users included</li>
          <li>VR Quality Ultra-HD</li>
          <li>Phone and email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="w-100 btn btn-lg btn-primary">
          <a href="mailto:tripal.tinvr@gmail.com">Contact us</a>
        </button>
      </div>
    </div>
  </div>
</div>

<h2 class="display-6 text-center mb-4">Compare plans</h2>

<div class="table-responsive">
  <table class="table text-center">
    <thead>
      <tr>
        <th style="width: 34%"></th>
        <th style="width: 22%">Free</th>
        <th style="width: 22%">Pro</th>
        <th style="width: 22%">Enterprise</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row" class="text-start">Public</th>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
      </tr>
      <tr>
        <th scope="row" class="text-start">Private</th>
        <td></td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
      </tr>
    </tbody>

    <tbody>
      <tr>
        <th scope="row" class="text-start">Permissions</th>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
      </tr>
      <tr>
        <th scope="row" class="text-start">Sharing</th>
        <td></td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
      </tr>
      <tr>
        <th scope="row" class="text-start">Unlimited members</th>
        <td></td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
      </tr>
      <tr>
        <th scope="row" class="text-start">Extra security</th>
        <td></td>
        <td></td>
        <td>
          <svg class="bi" width="24" height="24">
            <use xlink:href="#check" />
          </svg>
        </td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock %}

backend/project/home/templates/show_posts.html
{% extends "base.html" %} {% block content %}

<!-- post form -->
<h3>Add a Post!</h3>
<br />
<form class="form-message" role="form" method="post" action="/">
  {{ form.csrf_token }}
  <p>
    {{ form.title(placeholder="title") }}
    <span class="error">
      {% if form.title.errors %} {% for error in form.title.errors %} {{ error
      }} {% endfor %} {% endif %}
    </span>
  </p>
  <p>
    {{ form.description(placeholder="description") }}
    <span class="error">
      {% if form.description.errors %} {% for error in form.description.errors
      %} {{ error }} {% endfor %} {% endif %}
    </span>
  </p>
  <button class="btn btn-sm btn-success" type="submit">Post</button>
</form>

<!-- All posts -->
<h3>Posts:</h3>
{% for post in posts %}
<strong>Title:</strong> {{ post.title }} <br />
<strong>Post:</strong> {{ post.description }} <br />
<strong>Author:</strong> {{ post.author.name }} <br />
<br />
{% endfor %} {% endblock %}

backend/project/home/templates/vr.html
{% extends "base.html" %} {% block content %}

<h1 style="text-align: center">Welcome to TriPal VR Visits!</h1>
<br />
<center>
  <img
    src="{{ url_for('static', filename='images/tinvr.png') }}"
    height="600"
  />
</center>
<h1 style="text-align: center">Coming Sooooooon!</h1>

{% endblock %}

backend/project/home/templates/welcome.html
{% extends "base.html" %} {% block content %}

<h1>Welcome to Flask!</h1>
<br />
<p>Click <a href="{{ url_for('home.home') }}">here</a> to go home.</p>

{% endblock %}